### ISSUE TITLE
bash script not working on windows machine 

### ISSUE THREAD

**Issue by cDanowski** [KomMonitor/docker#2]
while setting up a local test environment on a windows machine, the shell script located at https://github.com/KomMonitor/docker/blob/master/config/config.sh  is not working.

I got error messages like
```
2024-02-13 09:40:14 /code/config.sh: line 34: syntax error: unexpected end of file (expecting "then")
: not found09:41:15 /code/config.sh: line 2: 
2024-02-13 09:41:15 /code/config.sh: line 33: syntax error: unexpected "fi" (expecting "then")
```

solution is described here: https://stackoverflow.com/questions/20368781/anything-like-dos2unix-for-windows 

the porblem basically is, that the shell script is donwloaded and interpreted using a windows EOL/EOF way. Should make sure to be formatted using  UNIX EOF/EOL way.

I.e. the Notepad++ way was the golden solution:

```
Solved it trough Notepad++.

Go to: Edit -> EOL Conversion -> Unix.
```

we might want to edit the description or is there even an automatic way to deal with it?

**Comment by SebaDro** [comment]
Well, actually the file is UNIX EOF/EOL formatted. You may want to check your local git settings regarding [the end-of-line conversion](https://git-scm.com/docs/gitattributes#_end_of_line_conversion). Git clients on Windows machines tend to automatically convert LF to CRLF when cloning a remote repository.

**Comment by cDanowski** [comment]
good advice, thanks

**Comment by SebaDro** [comment]
To prevent the shell script from being converted on WIndows machines I added a [.gitattributes file](https://github.com/KomMonitor/docker/blob/master/.gitattributes) to the repo with one rule:

```
*.sh text eol=lf
```
Please, try to clone the project, again, and check if the shell script has LF line ending.

**Comment by SebaDro** [comment]
Seems to work as expected.
